name: Java CI with Gradle

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
       
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            -Pspring_jpa_hibernate_ddl-auto=create-drop
